const Data = {
    "DOB": "july 04 2001",
    "Email": "codebulletin@gmail.com",
    "Address": "New Delhi, India",
    "College": "Deshbandhu College",
    "Specialization": ["Full-Stack Development", "Machine Learning", "Data Science", "Deep Learning", "Software Devolpment"],
    "aboutme-top": "I am a third year BSc student in Delhi University.",
    "aboutme-bottom": "I have a youtube channel named Code Bulletin.",
    "Skills": ["Full Stack Web Development", "Machine Learning", "Deep Learning", "Software Devlopment"],
    "Languages": ["C", "C++", "Python", "CSS", "SASS", "HTML5", "Javascript", "PHP", "Java", "Processing", "Markdown", "Shellscript", "Rust", "R", "Julia", "Mathematica", "Maxima", "Typescript", "Fortran", "C#"],
    "APIs": ["React", "React Native", "Redux", "Nodejs", "Express", "Tailwind", "Bootstrap", "P5", "SQL", "MongoDB", "Redis", "django", "GIT", "Tensorflow", "Keras", "Scikit", "Numpy", "Matplotlib", "Pandas", "SFML", "OpenGL", "Vulkan", "PyGame"]
}

const Skills = {
    "C++": "Expert",
    "Python": "Expert",
    "SFML": "Expert",
    "Processing": "Expert",
    "C": "Advance",
    "HTML": "Advance",
    "CSS": "Advance",
    "PHP": "Advance",
    "SASS": "Advance",
    "Tensorflow": "Advance",
    "Keras": "Advance",
    "Numpy": "Advance",
    "Matplotlib": "Advance",
    "Pandas": "Advance",
    "Javascript": "Advance",
    "SQL": "Advance",
    "SQLite": "Advance",
    "GIT": "Advance",
    "OpenGL": "Advance",
    "P5.js": "Advance",
    "C#": "Intermediate",
    "Java": "Intermediate",
    "Rust": "Intermediate",
    "Scikit": "Intermediate",
    "Tailwind": "Intermediate",
    "Bootstrap": "Intermediate",
    "React": "Intermediate",
    "React Native": "Intermediate",
    "Redux": "Intermediate",
    "Nodejs": "Intermediate",
    "Express": "Intermediate",
    "MongoDB": "Intermediate",
    "django": "Intermediate",
    "Vulkan": "Intermediate",
    "PyGame": "Intermediate",
    "Markdown": "Intermediate",
    "Shellscript": "Intermediate",
    "Fortran": "Beginner",
    "Typescript": "Beginner",
    "Redis": "Beginner",
    "R": "Beginner",
    "Julia": "Beginner",
}